/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as publicBlogIndexRouteImport } from './routes/(public)/blog.index'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as publicBlogSlugRouteImport } from './routes/(public)/blog.$slug'

const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicBlogIndexRoute = publicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => publicRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicBlogSlugRoute = publicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => publicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/rss.xml': typeof RssDotxmlRoute
  '/about': typeof publicAboutRoute
  '/': typeof publicIndexRoute
  '/blog/$slug': typeof publicBlogSlugRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/blog/': typeof publicBlogIndexRoute
}
export interface FileRoutesByTo {
  '/rss.xml': typeof RssDotxmlRoute
  '/about': typeof publicAboutRoute
  '/': typeof publicIndexRoute
  '/blog/$slug': typeof publicBlogSlugRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/blog': typeof publicBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/(public)/about': typeof publicAboutRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/blog/$slug': typeof publicBlogSlugRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/(public)/blog/': typeof publicBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/rss.xml'
    | '/about'
    | '/'
    | '/blog/$slug'
    | '/api/rpc/$'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/rss.xml' | '/about' | '/' | '/blog/$slug' | '/api/rpc/$' | '/blog'
  id:
    | '__root__'
    | '/(public)'
    | '/rss.xml'
    | '/(public)/about'
    | '/(public)/'
    | '/(public)/blog/$slug'
    | '/api/rpc/$'
    | '/(public)/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  RssDotxmlRoute: typeof RssDotxmlRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/blog/': {
      id: '/(public)/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof publicBlogIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/blog/$slug': {
      id: '/(public)/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof publicBlogSlugRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicAboutRoute: typeof publicAboutRoute
  publicIndexRoute: typeof publicIndexRoute
  publicBlogSlugRoute: typeof publicBlogSlugRoute
  publicBlogIndexRoute: typeof publicBlogIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicAboutRoute: publicAboutRoute,
  publicIndexRoute: publicIndexRoute,
  publicBlogSlugRoute: publicBlogSlugRoute,
  publicBlogIndexRoute: publicBlogIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  RssDotxmlRoute: RssDotxmlRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
